const photos = [
    { url: "Album_IMG/1.webp", tags: ["Greek", "Alexander", "Egypt"], description: "Alexander the Great during Egypt conquest" },
    { url: "Album_IMG/2.webp", tags: ["Cleopatra", "Ceasar", "Egypt"], description: "Cleopatra and Ceasar together" },
    { url: "Album_IMG/3.webp", tags: ["Aztec", "Quetzalcoatl", "Mythology"], description: "Quetzalcoatl, the Aztec feathered serpent god" },
    { url: "Album_IMG/4.webp", tags: ["Greek", "Aphrodite", "Beauty"], description: "Aphrodite, Greek goddess of beauty" },
    { url: "Album_IMG/5.webp", tags: ["Futuristic", "City", "Architecture"], description: "A futuristic city skyline" },
    { url: "Album_IMG/6.webp", tags: ["Egypt", "Pharaoh", "Cartoon"], description: "Cartoon-style Egyptian pharaohs" },
    { url: "Album_IMG/7.webp", tags: ["Rome", "Emperor", "Cartoon"], description: "A cartoonized Roman emperor" },
    { url: "Album_IMG/8.webp", tags: ["Aztec", "Warrior", "Soldier"], description: "An Aztec warrior in battle gear" },
    { url: "Album_IMG/9.webp", tags: ["Rome", "Roads", "Engineering"], description: "Romans constructing roads" },
    { url: "Album_IMG/10.webp", tags: ["Aztec", "Warrior", "Battle"], description: "An Aztec soldier preparing for war" },
    { url: "Album_IMG/11.webp", tags: ["Sparta", "Soldiers", "Battle"], description: "Spartan soldiers marching to war" },
    { url: "Album_IMG/12.webp", tags: ["Aztec", "Pyramid", "Skyline"], description: "Skyline view from an Aztec pyramid" },
    { url: "Album_IMG/13.webp", tags: ["Greek", "Ship", "Storm"], description: "A Greek ship caught in a thunderstorm" },
    { url: "Album_IMG/14.webp", tags: ["Sparta", "Birth", "Tradition"], description: "The birth of a Spartan child" },
    { url: "Album_IMG/15.webp", tags: ["Aztec", "Merchants", "Economy"], description: "Aztec merchants using coffee beans as money" },
    { url: "Album_IMG/16.webp", tags: ["Dacia", "Burebista", "King"], description: "Burebista, the Dacian king" },
    { url: "Album_IMG/17.webp", tags: ["Egypt", "Cleopatra", "Beauty"], description: "A beautiful depiction of Cleopatra" },
    { url: "Album_IMG/18.webp", tags: ["Rome", "Colosseum", "Night"], description: "View of the Colosseum at night" },
    { url: "Album_IMG/19.webp", tags: ["WW2", "General", "Speech"], description: "A WW2 general giving a speech" },
    { url: "Album_IMG/20.webp", tags: ["Greek", "Hermes", "God"], description: "Hermes, the Greek god of speed" },
    { url: "Album_IMG/21.webp", tags: ["Greek", "Athletes", "Coronation"], description: "Coronation of young Greek athletes" },
    { url: "Album_IMG/22.webp", tags: ["Greek", "Apollo", "God"], description: "Apollo, Greek god of music and light" },
    { url: "Album_IMG/23.webp", tags: ["Greek", "Ares", "War"], description: "Ares, the Greek god of war" },
    { url: "Album_IMG/24.webp", tags: ["Greek", "Artemis", "Goddess"], description: "Artemis, Greek goddess of the hunt" },
    { url: "Album_IMG/25.webp", tags: ["Greek", "Dionysus", "Wine"], description: "Dionysus, Greek god of wine and festivity" },
    { url: "Album_IMG/26.webp", tags: ["Greek", "Hades", "Underworld"], description: "Hades, Greek god of the underworld" },
    { url: "Album_IMG/27.webp", tags: ["Greek", "Poseidon", "Sea"], description: "Poseidon, Greek god of the sea" },
    { url: "Album_IMG/28.webp", tags: ["Greek", "Zeus", "Thunder"], description: "Zeus, the king of the Greek gods" },
    { url: "Album_IMG/29.webp", tags: ["WW2", "Troops", "Inspection"], description: "WW2 general inspecting troops on the field" },
    { url: "Album_IMG/30.webp", tags: ["Rome", "Caesar", "Emperor"], description: "Julius Caesar, Roman emperor" },
    { url: "Album_IMG/31.webp", tags: ["Rome", "Caesar", "Armor"], description: "Caesar wearing his battle armor" },
    { url: "Album_IMG/32.webp", tags: ["Rome", "Caesar", "Assassination"], description: "The assassination of Julius Caesar" },
    { url: "Album_IMG/33.webp", tags: ["Rome", "Legionary", "Family"], description: "A Roman legionary with his family" },       
    { url: "album_img/34.webp", tags: ["WW2", "Ribbentrop", "Molotov"], description: "Depiction of the Ribbentrop-Molotov Pact" },
    { url: "album_img/35.webp", tags: ["Egypt", "Nile", "Valley"], description: "The Valley of the Nile" },
    { url: "album_img/36.webp", tags: ["Rome", "Legionary", "Rest"], description: "An old Roman legionary resting" },
    { url: "album_img/37.webp", tags: ["Egypt", "Pharaoh", "Army"], description: "An Egyptian pharaoh leading his army" },
    { url: "album_img/38.webp", tags: ["Princess", "Beauty", "Royalty"], description: "A beautiful princess" },
    { url: "album_img/39.webp", tags: ["Aztec", "Prisoners", "War"], description: "Aztec prisoners of war" },
    { url: "album_img/40.webp", tags: ["Egypt", "Pharaoh", "Royalty"], description: "An Egyptian pharaoh" },
    { url: "album_img/41.webp", tags: ["Greece", "Socrates", "Speech"], description: "Socrates giving a speech" },
    { url: "album_img/42.webp", tags: ["WW2", "Soldiers", "City"], description: "WW2 soldiers entering a city" },
    { url: "album_img/43.webp", tags: ["WW2", "Soviet", "Council"], description: "Soviet war council during WW2" },
    { url: "album_img/44.webp", tags: ["Aztec", "Eclipse", "Sun"], description: "A solar eclipse from an Aztec perspective" },
    { url: "album_img/45.webp", tags: ["Greece", "Storm", "Thunder"], description: "A thunderstorm over Greece" },
    { url: "album_img/46.webp", tags: ["WW2", "Tank", "Tiger"], description: "A WW2 Tiger tank in battle" },
    { url: "album_img/48.webp", tags: ["WW2", "General", "Orders"], description: "A WW2 general reviewing documents" },
    { url: "album_img/49.webp", tags: ["Cartoon", "Animal", "Cute"], description: "A cute cartoonized puppy" },
    { url: "album_img/50.webp", tags: ["Cartoon", "Animal", "Fluffy"], description: "A cute cartoonized fluffy puppy" },
    { url: "Album_IMG/51.webp", tags: ["Cabin", "Lake", "Nature"], description: "A cabin by a peaceful lake" },
    { url: "Album_IMG/52.webp", tags: ["Bee", "Convertible", "Vacation"], description: "A cartoon bee in a convertible" },
    { url: "Album_IMG/53.webp", tags: ["Castle", "Mountains", "Fantasy"], description: "A fantasy castle on the mountains" },
    { url: "Album_IMG/54.webp", tags: ["Dragon", "Cliff", "Fantasy"], description: "A red dragon on a cliff" },
    { url: "Album_IMG/55.webp", tags: ["Abandoned", "Castle", "Frozen Lake"], description: "An abandoned castle on a frozen lake" },
    { url: "Album_IMG/56.webp", tags: ["Hagrid", "Young", "Fantasy"], description: "A young Hagrid in a magical world" },
    { url: "Album_IMG/57.webp", tags: ["Voldemort", "Young", "Villain"], description: "A young Voldemort with a dark look" }
];           