const photos = [
    { url: "Album_IMG/1.webp", tags: ["Greek", "Alexander", "Egypt"], description: "Alexander the Great during Egypt conquest" },
    { url: "Album_IMG/2.webp", tags: ["Cleopatra", "Ceasar", "Egypt"], description: "Cleopatra and Ceasar together" },
    { url: "Album_IMG/3.webp", tags: ["Aztec", "Quetzalcoatl", "Mythology"], description: "Quetzalcoatl, the Aztec feathered serpent god" },
    { url: "Album_IMG/4.webp", tags: ["Greek", "Aphrodite", "Beauty"], description: "Aphrodite, Greek goddess of beauty" },
    { url: "Album_IMG/5.webp", tags: ["Futuristic", "City", "Architecture"], description: "A futuristic city skyline" },
    { url: "Album_IMG/6.webp", tags: ["Egypt", "Pharaoh", "Cartoon"], description: "Cartoon-style Egyptian pharaohs" },
    { url: "Album_IMG/7.webp", tags: ["Rome", "Emperor", "Cartoon"], description: "A cartoonized Roman emperor" },
    { url: "Album_IMG/8.webp", tags: ["Aztec", "Warrior", "Soldier"], description: "An Aztec warrior in battle gear" },
    { url: "Album_IMG/9.webp", tags: ["Rome", "Roads", "Engineering"], description: "Romans constructing roads" },
    { url: "Album_IMG/10.webp", tags: ["Aztec", "Warrior", "Battle"], description: "An Aztec soldier preparing for war" },
    { url: "Album_IMG/11.webp", tags: ["Sparta", "Soldiers", "Battle"], description: "Spartan soldiers marching to war" },
    { url: "Album_IMG/12.webp", tags: ["Aztec", "Pyramid", "Skyline"], description: "Skyline view from an Aztec pyramid" },
    { url: "Album_IMG/13.webp", tags: ["Greek", "Ship", "Storm"], description: "A Greek ship caught in a thunderstorm" },
    { url: "Album_IMG/14.webp", tags: ["Sparta", "Birth", "Tradition"], description: "The birth of a Spartan child" },
    { url: "Album_IMG/15.webp", tags: ["Aztec", "Merchants", "Economy"], description: "Aztec merchants using coffee beans as money" },
    { url: "Album_IMG/16.webp", tags: ["Dacia", "Burebista", "King"], description: "Burebista, the Dacian king" },
    { url: "Album_IMG/17.webp", tags: ["Egypt", "Cleopatra", "Beauty"], description: "A beautiful depiction of Cleopatra" },
    { url: "Album_IMG/18.webp", tags: ["Rome", "Colosseum", "Night"], description: "View of the Colosseum at night" },
    { url: "Album_IMG/19.webp", tags: ["WW2", "General", "Speech"], description: "A WW2 general giving a speech" },
    { url: "Album_IMG/20.webp", tags: ["Greek", "Hermes", "God"], description: "Hermes, the Greek god of speed" },
    { url: "Album_IMG/21.webp", tags: ["Greek", "Athletes", "Coronation"], description: "Coronation of young Greek athletes" },
    { url: "Album_IMG/22.webp", tags: ["Greek", "Apollo", "God"], description: "Apollo, Greek god of music and light" },
    { url: "Album_IMG/23.webp", tags: ["Greek", "Ares", "War"], description: "Ares, the Greek god of war" },
    { url: "Album_IMG/24.webp", tags: ["Greek", "Artemis", "Goddess"], description: "Artemis, Greek goddess of the hunt" },
    { url: "Album_IMG/25.webp", tags: ["Greek", "Dionysus", "Wine"], description: "Dionysus, Greek god of wine and festivity" },
    { url: "Album_IMG/26.webp", tags: ["Greek", "Hades", "Underworld"], description: "Hades, Greek god of the underworld" },
    { url: "Album_IMG/27.webp", tags: ["Greek", "Poseidon", "Sea"], description: "Poseidon, Greek god of the sea" },
    { url: "Album_IMG/28.webp", tags: ["Greek", "Zeus", "Thunder"], description: "Zeus, the king of the Greek gods" },
    { url: "Album_IMG/29.webp", tags: ["WW2", "Troops", "Inspection"], description: "WW2 general inspecting troops on the field" },
    { url: "Album_IMG/30.webp", tags: ["Rome", "Caesar", "Emperor"], description: "Julius Caesar, Roman emperor" },
    { url: "Album_IMG/31.webp", tags: ["Rome", "Caesar", "Armor"], description: "Caesar wearing his battle armor" },
    { url: "Album_IMG/32.webp", tags: ["Rome", "Caesar", "Assassination"], description: "The assassination of Julius Caesar" },
    { url: "Album_IMG/33.webp", tags: ["Rome", "Legionary", "Family"], description: "A Roman legionary with his family" },       
    { url: "album_img/34.webp", tags: ["WW2", "Ribbentrop", "Molotov"], description: "Depiction of the Ribbentrop-Molotov Pact" },
    { url: "album_img/35.webp", tags: ["Egypt", "Nile", "Valley"], description: "The Valley of the Nile" },
    { url: "album_img/36.webp", tags: ["Rome", "Legionary", "Rest"], description: "An old Roman legionary resting" },
    { url: "album_img/37.webp", tags: ["Egypt", "Pharaoh", "Army"], description: "An Egyptian pharaoh leading his army" },
    { url: "album_img/38.webp", tags: ["Princess", "Beauty", "Royalty"], description: "A beautiful princess" },
    { url: "album_img/39.webp", tags: ["Aztec", "Prisoners", "War"], description: "Aztec prisoners of war" },
    { url: "album_img/40.webp", tags: ["Egypt", "Pharaoh", "Royalty"], description: "An Egyptian pharaoh" },
    { url: "album_img/41.webp", tags: ["Greece", "Socrates", "Speech"], description: "Socrates giving a speech" },
    { url: "album_img/42.webp", tags: ["WW2", "Soldiers", "City"], description: "WW2 soldiers entering a city" },
    { url: "album_img/43.webp", tags: ["WW2", "Soviet", "Council"], description: "Soviet war council during WW2" },
    { url: "album_img/44.webp", tags: ["Aztec", "Eclipse", "Sun"], description: "A solar eclipse from an Aztec perspective" },
    { url: "album_img/45.webp", tags: ["Greece", "Storm", "Thunder"], description: "A thunderstorm over Greece" },
    { url: "album_img/46.webp", tags: ["WW2", "Tank", "Tiger"], description: "A WW2 Tiger tank in battle" },
    { url: "album_img/48.webp", tags: ["WW2", "General", "Orders"], description: "A WW2 general reviewing documents" },
    { url: "album_img/49.webp", tags: ["Cartoon", "Animal", "Cute"], description: "A cute cartoonized puppy" },
    { url: "album_img/50.webp", tags: ["Cartoon", "Animal", "Fluffy"], description: "A cute cartoonized fluffy puppy" },
    { url: "Album_IMG/51.webp", tags: ["Cabin", "Lake", "Nature"], description: "A cabin by a peaceful lake" },
    { url: "Album_IMG/52.webp", tags: ["Bee", "Convertible", "Vacation"], description: "A cartoon bee in a convertible" },
    { url: "Album_IMG/53.webp", tags: ["Castle", "Mountains", "Fantasy"], description: "A fantasy castle on the mountains" },
    { url: "Album_IMG/54.webp", tags: ["Dragon", "Cliff", "Fantasy"], description: "A red dragon on a cliff" },
    { url: "Album_IMG/55.webp", tags: ["Abandoned", "Castle", "Frozen Lake"], description: "An abandoned castle on a frozen lake" },
    { url: "Album_IMG/56.webp", tags: ["Hagrid", "Young", "Fantasy"], description: "A young Hagrid in a magical world" },
    { url: "Album_IMG/57.webp", tags: ["Voldemort", "Young", "Villain"], description: "A young Voldemort with a dark look" },
    { url: "Album_IMG/58.webp", tags: ["Redhead", "Model", "Beauty"], description: "A beautiful redhead model with striking features" },  
    { url: "Album_IMG/59.webp", tags: ["Silver Hair", "Portrait", "Model"], description: "A stunning portrait of a model with silver hair" },  
    { url: "Album_IMG/60.webp", tags: ["Black Model", "Dark Hair", "Portrait"], description: "A beautiful portrait of a black model with dark hair" },  
    { url: "Album_IMG/61.webp", tags: ["New York", "1960s", "Streets"], description: "A nostalgic view of New York streets in the 1960s" },  
    { url: "Album_IMG/62.webp", tags: ["Retro", "Japan", "Street"], description: "A vintage street scene capturing the charm of retro Japan" },  
    { url: "Album_IMG/63.webp", tags: ["Tokyo", "Nightlife", "Modern"], description: "A vibrant look at modern Tokyo nightlife" },  
    { url: "Album_IMG/64.webp", tags: ["Medieval", "Tokyo", "Historical"], description: "A fascinating depiction of medieval Tokyo" }, 
    { url: "Album_IMG/65.webp", tags: ["WW2", "D-Day", "Soldiers"], description: "American soldiers landing on D-Day" },
    { url: "Album_IMG/66.webp", tags: ["Harry Potter", "Diagon Alley", "Magic"], description: "The magical streets of Diagon Alley" },
    { url: "Album_IMG/67.webp", tags: ["Harry Potter", "Draco Malfoy", "Hogwarts"], description: "Draco Malfoy in Hogwarts Hall" },
    { url: "Album_IMG/68.webp", tags: ["Avatar", "Na'vi", "Abandoned"], description: "Na'vi exploring a human ruin" },
    { url: "Album_IMG/69.webp", tags: ["Mystery", "Glasses", "Character"], description: "A mysterious figure with special glasses" },
    { url: "Album_IMG/70.webp", tags: ["Futuristic", "Tokyo", "Holograms"], description: "A high-tech Tokyo filled with holograms" },
    { url: "Album_IMG/71.webp", tags: ["Brazil", "Christ", "Wonder"], description: "The Christ the Redeemer statue in Brazil" },
    { url: "Album_IMG/72.webp", tags: ["Japan", "Tradition", "Modern"], description: "Japan balancing tradition and modernity" },
    { url: "Album_IMG/73.webp", tags: ["Brazil", "Favela", "Mafia"], description: "A glimpse into the Brazilian favela mafia" },
    { url: "Album_IMG/74.webp", tags: ["Italy", "Mafia", "Crime"], description: "The Sicilian mafia in Italy" },
    { url: "Album_IMG/75.webp", tags: ["Avatar", "Pandora", "Deep Sea"], description: "Mysterious deep-sea life on Pandora" },
    { url: "Album_IMG/76.webp", tags: ["Harry Potter", "Marauders", "Wedding"], description: "James and Lily Potter's wedding"},
    { url: "Album_IMG/77.webp", tags: ["Peaky Blinders", "Mafia", "Birmingham"], description: "Peaky Blinders in a 1920s Birmingham pub" },
    { url: "Album_IMG/78.webp", tags: ["Pandora", "Near-space", "POV"], description: "Pandora POW from near-space" },
    { url: "Album_IMG/79.webp", tags: ["Roman Empire", "Military", "Legionnaire", "Battle"], description: "Roman legionnaire on the frontline battle" },
    { url: "Album_IMG/80.webp", tags: ["Ancient Egypt", "Pyramids", "Giza", "Construction"], description: "Construction of the Great Pyramid of Giza" },
    { url: "Album_IMG/81.webp", tags: ["Futuristic", "Spaceship", "Space Exploration", "Planets"], description: "Futuristic spaceship exploring new planets" },
    { url: "Album_IMG/82.webp", tags: ["New York", "Mafia", "Organized Crime", "Times Square"], description: "New York Mafia meeting Times Square" },
    { url: "Album_IMG/83.webp", tags: ["Japan", "Auto Industry", "Booming Economy"], description: "Japan's booming Auto industry" },
    { url: "Album_IMG/84.webp", tags: ["Cabin", "Woods", "Lake", "Architecture"], description: "Architecture of a cabin in the woods near a lake" },
    { url: "Album_IMG/85.webp", tags: ["Avatar", "Na'vi", "Ceremony"], description: "Na'vi ceremony" },
    { url: "Album_IMG/86.webp", tags: ["Roman Empire", "Military", "Soldiers", "Payday"], description: "Roman soldiers payday" },
    { url: "Album_IMG/87.webp", tags: ["Roman Empire", "Military", "Soldiers", "Meal"], description: "Roman soldiers enjoying a meal before the battle" },
    { url: "Album_IMG/88.webp", tags: ["Roman Empire", "Military", "Soldier", "Family"], description: "Roman soldier missing his family" },
    { url: "Album_IMG/89.webp", tags: ["Avatar", "Na'vi", "Rider"], description: "Na'vi rider" },
    { url: "Album_IMG/90.webp", tags: ["Avatar", "Na'vi", "Ocean"], description: "Ocean Na'vi" },
    { url: "Album_IMG/91.webp", tags: ["Russia", "Mafia", "Organized Crime"], description: "Russian Mafia" },
    { url: "Album_IMG/92.webp", tags: ["China", "Great Wall", "Wall"], description: "The Great Chinese Wall" },
    { url: "Album_IMG/93.webp", tags: ["Gigantic", "Human", "Ship", "Pandora"], description: "Gigantic human ship landing on Pandora" },
    { url: "Album_IMG/94.webp", tags: ["Japan", "Yakuza", "Boss"], description: "Japanese Yakuza boss & members" },
    { url: "Album_IMG/95.webp", tags: ["Cartoonized", "Maradeurs", "Harry Potter"], description: "Cartoonized depiction of Marauders from Harry Potter" },
    { url: "Album_IMG/96.webp", tags: ["Hogwarts", "Students", "Library"], description: "Hogwarts students studying in library" },
    { url: "Album_IMG/97.webp", tags: ["Hogwarts", "Student", "Castle", "Boat"], description: "Hogwarts student arriving at the castle via boat" },
    { url: "Album_IMG/98.webp", tags: ["Cinematic", "Marauders", "Harry potter"], description: "cinematic shoot of marauders (Harry potter)" },
    { url: "Album_IMG/99.webp", tags: ["Pandora", "Stunning", "Nature"], description: "Pandora stunning nature" },
    { url: "Album_IMG/100.webp", tags: ["Severus Piton", "Alternate", "Old version"], description: "Severus Piton alternate old version" },
    { url: "Album_IMG/101.webp", tags: ["Voldemort", "Casting", "Spell"], description: "Voldemort casting a spell" },
    { url: "Album_IMG/102.webp", tags: ["Harry Potter", "Old version", "Returns", "Hogwarts"], description: "Harry Potter Old version returns at Hogwarts" },
    { url: "Album_IMG/103.webp", tags: ["Tokyo", "Skyline", "Cityscape"], description: "Tokyo Skyline" },
    { url: "Album_IMG/104.webp", tags: ["Harry Potter", "Hogwarts", "Friends", "Greeting"], description: "Old Harry potter being greeted by his former friends at hogwarts" },
    { url: "Album_IMG/105.webp", tags: ["Japan", "Train", "Station"], description: "Japanese train station" },
    { url: "Album_IMG/106.webp", tags: ["Yakuza", "Members", "Money"], description: "Yakuza members counting money" },
    { url: "Album_IMG/107.webp", tags: ["Cabin", "Woods"], description: "cabin in the woods" },
    { url: "Album_IMG/108.webp", tags: ["WW2", "Trench", "Attack"], description: "WW2 trench attack" },
    { url: "Album_IMG/109.webp", tags: ["Mysterious", "Character", "Wine"], description: "Mysterious character at a wine exhibition" },
    { url: "Album_IMG/110.webp", tags: ["Yakuza", "Members", "Shinjuku"], description: "Yakuza members in Shinjuku" },
    { url: "Album_IMG/111.webp", tags: ["Yakuza", "Boss", "Restaurant"], description: "Yakuza boss in restaurant" },
    { url: "Album_IMG/112.webp", tags: ["Yakuza", "Boss", "Cart"], description: "Yakuza boss in a shiny golden cart" },
    { url: "Album_IMG/113.webp", tags: ["Diagon Alley", "Shopping", "School"], description: "Diagon alley shopping day before school" },
    { url: "Album_IMG/114.webp", tags: ["Dragon", "Attack", "Targaryen"], description: "Dragon attacking Targaryen enemies" },
    { url: "Album_IMG/115.webp", tags: ["Dragon", "Protecting", "Loot"], description: "Dragon protecting the golden loot" },
    { url: "Album_IMG/116.webp", tags: ["Japanese", "Samurai", "Westerner", "Merchants"], description: "Japanese samurai meet westerner merchants" },
    { url: "Album_IMG/117.webp", tags: ["Medieval", "Castle", "Attack"], description: "Medieval castle attack" },
    { url: "Album_IMG/118.webp", tags: ["Lone", "Samurai", "Mountains"], description: "Lone samurai wandering trough the mountains" },
    { url: "Album_IMG/119.webp", tags: ["Na'vi", "Hunter", "Avatar"], description: "Na'vi hunter" },
    { url: "Album_IMG/120.webp", tags: ["Na'vi", "Avatar", "Rider"], description: "Na'vi Direhorse and his rider" },
    { url: "Album_IMG/121.webp", tags: ["Japan", "Samurai", "Fortress", "Assault"], description: "Assault on a Japanese fortress" },
    { url: "Album_IMG/122.webp", tags: ["Japan", "Samurai", "Bamboo", "Forest"], description: "Japan Samurai in a bamboo forest" },
    { url: "Album_IMG/123.webp", tags: ["Pirate", "Shipwreck", "Island"], description: "A lone pirate stranded on a deserted island after a shipwreck." },
    { url: "Album_IMG/124.webp", tags: ["Prisoner", "Shark", "Pirates", "Sea"], description: "A prisoner thrown into shark-infested waters by ruthless pirates." },
    { url: "Album_IMG/125.webp", tags: ["Japan", "Medieval", "Tea Master"], description: "A serene Japanese medieval tea master performing a ceremony." },
    { url: "Album_IMG/126.webp", tags: ["Conquistadores", "Amazon", "Rainforest"], description: "Conquistadores venturing into the depths of the Amazon rainforest." },
    { url: "Album_IMG/127.webp", tags: ["Lone Ranger", "Western", "Outlaw"], description: "The Lone Ranger standing tall against the Western frontier." },
    { url: "Album_IMG/128.webp", tags: ["Bounty Hunter", "Western", "Wanted"], description: "A rugged bounty hunter tracking down a wanted criminal in the Wild West." },
    { url: "Album_IMG/129.webp", tags: ["Ninja", "Night", "Convoy", "Japan"], description: "A stealthy ninja assaulting a convoy under the cover of night in feudal Japan." },
    { url: "Album_IMG/130.webp", tags: ["Fantasy", "Beast", "Forest", "Guardian"], description: "A majestic fantasy beast guarding the secrets of an ancient forest." },
    { url: "Album_IMG/131.webp", tags: ["Explorers", "Mapping", "New World", "Discovery"], description: "Explorers meticulously mapping the uncharted territories of the New World." },
    { url: "Album_IMG/132.webp", tags: ["Na'vi", "Avatar", "Swimming", "Ocean"], description: "A graceful Sea Na'vi swimming through the depths of Pandora's oceans." },
    { url: "Album_IMG/133.webp", tags: ["Fantasy", "Character", "Assassin", "Stealth"], description: "A mysterious fantasy assassin preparing for a covert operation." },
    { url: "Album_IMG/134.webp", tags: ["Conquistadores", "Natives", "First Contact", "Exploration"], description: "The dramatic first contact between conquistadores and indigenous natives." },
    { url: "Album_IMG/135.webp", tags: ["Black Hole", "Spaceship", "POV", "Cosmic"], description: "A breathtaking point-of-view from a spaceship approaching a black hole." },
    { url: "Album_IMG/136.webp", tags: ["Pirate", "Treasure", "Gold", "Wealth"], description: "A pirate greedily counting his hard-earned treasure." },
    { url: "Album_IMG/137.webp", tags: ["Pirate", "Government", "Peace Talks", "Negotiation"], description: "Peace talks between a pirate and a representative of the government." },
    { url: "Album_IMG/138.webp", tags: ["Japan", "Blacksmith", "Katana", "Medieval"], description: "A skilled Japanese blacksmith forging a katana with traditional techniques." },
    { url: "Album_IMG/139.webp", tags: ["Colonizing", "New World", "Artistic", "Historical"], description: "An artistic depiction of the complex process of colonizing the New World." },
    { url: "Album_IMG/140.webp", tags: ["Pirates", "Treasure", "Gold", "Discovery"], description: "Pirates celebrating their discovery of a hidden treasure trove of gold." },
    { url: "Album_IMG/141.webp", tags: ["Dwarf", "Forge", "Mountain"], description: "Dwarves forging weapons deep within a mountain." },
    { url: "Album_IMG/142.webp", tags: ["Europeans", "Native Americans", "Encounter"], description: "A historic meeting between Europeans and Native Americans." },
    { url: "Album_IMG/143.webp", tags: ["Futuristic", "City", "Flying Machines"], description: "A futuristic cityscape with flying vehicles and drones." },
    { url: "Album_IMG/144.webp", tags: ["Na'vi", "Ilu", "Ocean"], description: "A Na'vi riding an Ilu (a large aquatic creature) beneath the ocean's surface." },
    { url: "Album_IMG/145.webp", tags: ["New York", "Interwar", "Construction"], description: "The bustling construction of New York City during the interwar period." },
    { url: "Album_IMG/146.webp", tags: ["Expedition", "Forest", "Magic"], description: "An expedition venturing through a magical and mystical forest." },
    { url: "Album_IMG/147.webp", tags: ["Pirate", "Capture", "Ship"], description: "A notorious pirate captain captured by rival forces." },
    { url: "Album_IMG/148.webp", tags: ["Samurai", "Firearms", "Japan"], description: "Japanese samurai encountering and reacting to firearms for the first time." },
    { url: "Album_IMG/149.webp", tags: ["Mars", "Rover", "Exploration"], description: "A Mars rover exploring the red planet's surface." },
    { url: "Album_IMG/150.webp", tags: ["Aegon", "Balerion", "Fire"], description: "Aegon I Targaryen and his dragon Balerion burning the city of Harrenhall." },
    { url: "Album_IMG/151.webp", tags: ["Explorer", "Africa", "Map"], description: "An explorer receiving guidance from natives and mapping their discoveries in Africa." },
    { url: "Album_IMG/152.webp", tags: ["Japan", "Rice Field", "Rural"], description: "A picturesque view of Japanese rice fields." },
    { url: "Album_IMG/153.webp", tags: ["Robert Baratheon", "Rebellion", "Army"], description: "A young Robert Baratheon leading his army during Robert's Rebellion." },
    { url: "Album_IMG/154.webp", tags: ["Cowboy", "Campfire", "Stars"], description: "A cowboy enjoying a campfire under a breathtaking night sky." },
    { url: "Album_IMG/155.webp", tags: ["Na'vi", "Children", "Floating Mountains"], description: "Young Na'vi children playing joyfully amongst the floating mountains of Pandora." },
    { url: "Album_IMG/156.webp", tags: ["Dragon Hunter", "Dragon", "Battle"], description: "A skilled dragon hunter facing a colossal and fearsome dragon." },
    { url: "Album_IMG/157.webp", tags: ["Human", "Na'vi", "Tree", "Attack"], description: "Humans attacking the sacred Tree of Souls on Pandora." },
    { url: "Album_IMG/158.webp", tags: ["Berlin", "WW2", "Destruction"], description: "The devastation of Berlin during the final days of World War II." },
    { url: "Album_IMG/159.webp", tags: ["Fairy", "Princess", "Fantasy"], description: "A beautiful fairy princess in a magical realm." },
    { url: "Album_IMG/160.webp", tags: ["Samurai", "Seppuku", "Honor"], description: "A samurai preparing for seppuku after a dishonorable defeat." },
    { url: "Album_IMG/161.webp", tags: ["WW2", "Dogfight", "Sea Lion"], description: "Dogfight during Operation Sea Lion." },
    { url: "Album_IMG/162.webp", tags: ["Sheriff", "Town", "Western"], description: "Sheriff arrives in town." },
    { url: "Album_IMG/163.webp", tags: ["Valyria", "Cataclysm", "Ruins"], description: "Valyria's cataclysm." },
    { url: "Album_IMG/164.webp", tags: ["Feudal Japan", "Port", "Trade"], description: "A feudal Japanese port." },
    { url: "Album_IMG/165.webp", tags: ["Caribbean", "Sharks", "Danger"], description: "Shark-infested Caribbean waters." },
    { url: "Album_IMG/166.webp", tags: ["Fantasy", "Battle", "Epic"], description: "An epic fantasy battle." },
    { url: "Album_IMG/167.webp", tags: ["Na'vi", "Village", "Jungle"], description: "Abandoned Na'vi village." },
    { url: "Album_IMG/168.webp", tags: ["Na'vi", "Hunter", "Focus"], description: "Na'vi hunter prepares to strike." },
    { url: "Album_IMG/169.webp", tags: ["Daenerys", "Dragons", "Slaves"], description: "Daenerys liberates slaves." },
    { url: "Album_IMG/170.webp", tags: ["Human", "Na'vi", "Assault", "Pandora"], description: "Human-Na'vi assault on humans." },
    { url: "Album_IMG/171.webp", tags: ["Cowboy", "Storm", "Cattle"], description: "Cowboy searches for cattle in a storm." },
    { url: "Album_IMG/172.webp", tags: ["Samurai", "Emperor", "Audition"], description: "Samurai auditions for the Emperor." },
    { url: "Album_IMG/173.webp", tags: ["Human Colony", "Saturn", "Moon"], description: "Human colony on a Saturn moon." },
    { url: "Album_IMG/174.webp", tags: ["Fantasy", "Hunter", "Adventure"], description: "A fantasy hunter on a quest." },
    { url: "Album_IMG/175.webp", tags: ["Pirates", "Treasure", "Secret"], description: "Pirates hide their treasure." },
    { url: "Album_IMG/176.webp", tags: ["Tokyo", "Neon", "Nightlife"], description: "Neon-lit Tokyo nightlife." },
    { url: "Album_IMG/177.webp", tags: ["Feudal Japan", "Market", "Trade"], description: "A feudal Japanese market." },
    { url: "Album_IMG/178.webp", tags: ["Samurai", "Geisha", "Japan"], description: "Samurai and geisha companion." },
    { url: "Album_IMG/179.webp", tags: ["Japan", "Temple", "Jungle"], description: "Japanese temple in a jungle." },
    { url: "Album_IMG/180.webp", tags: ["Elven", "Village", "Magic"], description: "A magical elven village." },
    { url: "Album_IMG/181.webp", tags: ["Dragon Rider", "Warrior", "Fantasy"], description: "A dragon rider warrior." },
    { url: "Album_IMG/182.webp", tags: ["Western", "Train", "Bandits"], description: "Bandits assault a train." },
    { url: "Album_IMG/183.webp", tags: ["Frost Elf", "Sorcerer", "Magic"], description: "A Frost Elf sorcerer." },
    { url: "Album_IMG/184.webp", tags: ["Pirate", "Ship", "Assault"], description: "Pirates assault a ship." },
    { url: "Album_IMG/185.webp", tags: ["Mars", "Colony", "Advanced"], description: "Advanced human colony on Mars." },
    { url: "Album_IMG/186.webp", tags: ["Elven", "Nobility", "Feast"], description: "Elven nobility at a feast." },
    { url: "Album_IMG/187.webp", tags: ["Maya", "Ruins", "Jungle"], description: "Hidden Mayan ruins." },
    { url: "Album_IMG/188.webp", tags: ["Knight", "Wizard", "Battle"], description: "Knight battles a dark wizard." },
    { url: "Album_IMG/189.webp", tags: ["Mars", "City", "Sandstorm"], description: "Human city on Mars during a sandstorm." },
    { url: "Album_IMG/190.webp", tags: ["Fire Na'vi", "Volcano", "Pandora"], description: "Fire Na'vi near a volcano." },
    { url: "Album_IMG/191.webp", tags: ["Conquistadores", "Jungle", "Adventure"], description: "Conquistadores in the jungle." },
    { url: "Album_IMG/192.webp", tags: ["Space Station", "Human", "Orbital"], description: "A human orbital station." },
    { url: "Album_IMG/193.webp", tags: ["Samurai", "Mountains", "Japan"], description: "Samurai in the Japanese mountains." },
    { url: "Album_IMG/194.webp", tags: ["Aegon", "Sisters", "Battle Plan"], description: "Aegon and sisters plan battle." },
    { url: "Album_IMG/195.webp", tags: ["Human Colony", "New World", "America"], description: "Human colony in the New World." },
    { url: "Album_IMG/196.webp", tags: ["Gringotts", "Bank", "Magic"], description: "Gringotts Wizarding Bank." },
    { url: "Album_IMG/197.webp", tags: ["Winterfell", "Winter", "Game of Thrones"], description: "Winterfell during winter." }
    ];
    
           